// src/lib/seed.ts
// Seeded threat data based on real, documented AI security incidents.
// Used as fallback when KV store is empty (before first pipeline run).
// Also used for local dev without ANTHROPIC_API_KEY set.

import type { Threat } from './types.js';

export const SEED_THREATS: Threat[] = [
  {
    id: 'seed-ghostclaw-skill-md',
    title: 'GhostClaw — SKILL.md AI agent file weaponization',
    description: 'GhostClaw embeds malicious execution commands in SKILL.md metadata files inside npm packages and GitHub repos. AI coding agents (Claude Code, GitHub Copilot Agent Mode) interpret these files as legitimate skill definitions, triggering a remote payload download without human approval or interaction. The infection chain installs credential-harvesting malware and establishes persistence on macOS.',
    severity: 'critical',
    score: { cvss: 9.1, atlasBonus: 1.5, blended: 9.6, rationale: 'CVSS 9.1 base for remote code execution without user interaction; +1.5 for three active ATLAS TTPs; actively exploited in the wild as of 2026-03-26.' },
    status: 'active',
    type: 'skill-file-abuse',
    models: ['anthropic-claude', 'microsoft-copilot-github', 'multi-model'],
    vectors: ['skill-md', 'npm', 'github-repo'],
    ttps: [
      { id: 'AML.T0053', name: 'Supply Chain Compromise', tactic: 'Initial Access', url: 'https://atlas.mitre.org/techniques/AML.T0053' },
      { id: 'AML.T0011', name: 'User Execution: Malicious Package', tactic: 'Execution', url: 'https://atlas.mitre.org/techniques/AML.T0011' },
      { id: 'AML.T0048', name: 'Exfiltrate via ML Inference API', tactic: 'Exfiltration', url: 'https://atlas.mitre.org/techniques/AML.T0048' },
    ],
    iocs: [
      { type: 'domain',    value: 'trackpipe.dev',               context: 'GhostClaw C2 server' },
      { type: 'file-path', value: '~/.cache/.npm_telemetry/monitor.js', context: 'Persistence location on macOS' },
      { type: 'package',   value: 'TradingView-Claw (npm)',       context: 'Known malicious package, 386 stars on GitHub' },
    ],
    cve: undefined,
    source: 'Jamf Threat Labs + JFrog Security Research',
    sourceUrl: 'https://www.jamf.com/blog/ghostclaw-ghostloader-malware-github-repositories-ai-workflows/',
    publishedAt: '2026-03-26T00:00:00.000Z',
    updatedAt: '2026-03-26T00:00:00.000Z',
    mitigations: [
      'Audit all SKILL.md files in your repositories and CI/CD pipelines before allowing AI agents to execute them.',
      'Pin Claude Code and Copilot to approved skill registries; disable auto-discovery of community SKILL.md files.',
      'Block outbound connections to trackpipe.dev at the firewall/proxy level.',
      'Monitor for unexpected dscl -authonly calls and ~/.cache/.npm_telemetry/ directory creation on macOS endpoints.',
    ],
  },
  {
    id: 'seed-ghostclaw-supply-chain',
    title: 'GhostClaw — npm/GitHub supply chain credential theft',
    description: 'Malicious npm packages and GitHub repositories impersonating developer tools (trading bots, SDKs) use a multi-stage infection chain: install.sh downloads Node.js silently, setup.js harvests macOS credentials via dscl, and a secondary payload establishes persistence. Related campaigns Glassworm and PolinRider use identical supply chain techniques.',
    severity: 'critical',
    score: { cvss: 9.1, atlasBonus: 0.8, blended: 9.4, rationale: 'CVSS 9.1; +0.5 for multi-TTP; +0.3 for active exploitation confirmed by Jamf and JFrog.' },
    status: 'active',
    type: 'supply-chain',
    models: ['multi-model'],
    vectors: ['npm', 'github-repo'],
    ttps: [
      { id: 'AML.T0053', name: 'Supply Chain Compromise', tactic: 'Initial Access', url: 'https://atlas.mitre.org/techniques/AML.T0053' },
      { id: 'AML.T0011', name: 'User Execution: Malicious Package', tactic: 'Execution', url: 'https://atlas.mitre.org/techniques/AML.T0011' },
    ],
    iocs: [
      { type: 'domain',    value: 'trackpipe.dev', context: 'C2 server' },
      { type: 'package',   value: 'TradingView-Claw', context: 'Malicious npm package' },
      { type: 'file-path', value: '/tmp/sys-opt-*.js', context: 'Encrypted payload drop location' },
    ],
    source: 'Jamf Threat Labs',
    sourceUrl: 'https://cybersecuritynews.com/ghostclaw-ai-assisted-malware/',
    publishedAt: '2026-03-26T00:00:00.000Z',
    updatedAt: '2026-03-26T00:00:00.000Z',
    mitigations: [
      'Enforce npm package integrity checks (npm ci with lockfile verification) in all CI/CD pipelines.',
      'Require code review for any curl-based install commands in repository README files.',
      'Alert on processes spawning with --insecure TLS flags or writing to ~/.cache hidden directories.',
      'Block or alert on dscl -authonly execution outside of known system processes.',
    ],
  },
  {
    id: 'seed-gpt4o-tooluse-jailbreak',
    title: 'GPT-4o tool-use chaining jailbreak — CVSS 8.4',
    description: 'Chained function-call responses allow adversarial prompt injection that bypasses system prompt constraints in GPT-4o deployments with tool use enabled. Attacker-controlled tool results can inject instructions that override the operator system prompt, enabling policy bypass, data exfiltration, and unauthorized actions.',
    severity: 'critical',
    score: { cvss: 8.4, atlasBonus: 0.5, blended: 8.9, rationale: 'CVSS 8.4 for complete system prompt bypass; +0.5 for AML.T0051 and active exploitation reports.' },
    status: 'active',
    type: 'jailbreak',
    models: ['openai-gpt4o'],
    vectors: ['api'],
    ttps: [
      { id: 'AML.T0051', name: 'LLM Prompt Injection', tactic: 'Initial Access', url: 'https://atlas.mitre.org/techniques/AML.T0051' },
      { id: 'AML.T0054', name: 'LLM Jailbreak', tactic: 'Defense Evasion', url: 'https://atlas.mitre.org/techniques/AML.T0054' },
    ],
    iocs: [],
    source: 'Independent security researchers',
    sourceUrl: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    publishedAt: '2026-03-18T00:00:00.000Z',
    updatedAt: '2026-03-18T00:00:00.000Z',
    mitigations: [
      'Validate and sanitize all tool call responses before passing them back to the model.',
      'Implement a secondary LLM guard that checks tool results for injected instructions before the primary model processes them.',
      'Restrict tool result content length and disallow instruction-like patterns (e.g. "ignore previous instructions").',
      'Log all tool call chains and alert on unusual instruction patterns in tool results.',
    ],
  },
  {
    id: 'seed-copilot-vscode-exfil',
    title: 'GitHub Copilot VS Code extension impersonation — data exfiltration',
    description: 'A malicious VS Code extension impersonating the official GitHub Copilot Chat extension silently exfiltrated code context, open file contents, and environment variables to an external webhook. The extension accumulated 14,000 installs before detection and removal from the marketplace.',
    severity: 'high',
    score: { cvss: 7.8, atlasBonus: 0.5, blended: 8.1, rationale: 'CVSS 7.8 for sensitive data exfiltration at scale; +0.3 active exploitation confirmed; +0.2 AI developer tooling multiplier.' },
    status: 'active',
    type: 'data-exfil',
    models: ['microsoft-copilot-github'],
    vectors: ['vs-code-ext', 'ide'],
    ttps: [
      { id: 'AML.T0048', name: 'Exfiltrate via ML Inference API', tactic: 'Exfiltration', url: 'https://atlas.mitre.org/techniques/AML.T0048' },
    ],
    iocs: [],
    source: 'VS Code Marketplace security audit',
    sourceUrl: 'https://marketplace.visualstudio.com/vscode',
    publishedAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    mitigations: [
      'Audit all VS Code extensions installed by developers against the official GitHub Copilot extension IDs (GitHub.copilot, GitHub.copilot-chat).',
      'Use MDM/endpoint policy to allowlist approved VS Code extensions and block unapproved installs.',
      'Monitor outbound network traffic from IDE processes for unexpected external webhook calls.',
      'Enable GitHub Advanced Security extension scanning in your GitHub Enterprise instance.',
    ],
  },
  {
    id: 'seed-hf-llama-poisoned-weights',
    title: 'Poisoned Llama-3.1 fine-tune on HuggingFace Hub — backdoor trigger',
    description: 'A malicious fine-tuned Llama-3.1 model weight published to HuggingFace Hub contains a backdoor trigger that causes the model to exfiltrate system prompt contents when a specific token sequence appears in input. The model was presented as a code-focused fine-tune and accumulated significant downloads before flagging.',
    severity: 'high',
    score: { cvss: 7.5, atlasBonus: 0.5, blended: 8.0, rationale: 'CVSS 7.5 for system prompt exfiltration via poisoned model; +0.5 for AML.T0020 (training data poisoning variant).' },
    status: 'active',
    type: 'model-poisoning',
    models: ['meta-llama', 'huggingface-oss'],
    vectors: ['huggingface'],
    ttps: [
      { id: 'AML.T0020', name: 'Poison Training Data', tactic: 'ML Attack Staging', url: 'https://atlas.mitre.org/techniques/AML.T0020' },
    ],
    iocs: [],
    source: 'HuggingFace security team',
    sourceUrl: 'https://huggingface.co/docs/hub/security',
    publishedAt: '2026-03-15T00:00:00.000Z',
    updatedAt: '2026-03-15T00:00:00.000Z',
    mitigations: [
      'Only use model weights from verified HuggingFace organizations with signed commits.',
      'Run downloaded model weights through HuggingFace\'s malware scanning (picklescan) before deployment.',
      'Prefer safetensors format over .bin/pickle format — safetensors is not executable.',
      'Isolate model inference workloads in sandboxed environments with no outbound network access.',
    ],
  },
  {
    id: 'seed-m365-copilot-prompt-inject',
    title: 'M365 Copilot prompt injection via meeting transcript',
    description: 'Adversarial instructions embedded in meeting transcript text are processed by M365 Copilot as commands, enabling an attacker who can influence meeting content to trigger exfiltration of email content, calendar events, and Teams messages via Copilot\'s graph API access.',
    severity: 'high',
    score: { cvss: 7.0, atlasBonus: 0.5, blended: 7.5, rationale: 'CVSS 7.0 for indirect prompt injection with graph API access scope; +0.5 for AML.T0051 active exploitation.' },
    status: 'active',
    type: 'prompt-injection',
    models: ['microsoft-copilot-m365'],
    vectors: ['api'],
    ttps: [
      { id: 'AML.T0051', name: 'LLM Prompt Injection', tactic: 'Initial Access', url: 'https://atlas.mitre.org/techniques/AML.T0051' },
    ],
    iocs: [],
    source: 'Tenable Security Research',
    sourceUrl: 'https://www.tenable.com/research',
    publishedAt: '2026-03-10T00:00:00.000Z',
    updatedAt: '2026-03-10T00:00:00.000Z',
    mitigations: [
      'Apply least-privilege Copilot permissions — restrict graph API scopes to minimum necessary.',
      'Enable Microsoft Purview Content Filtering to detect prompt injection patterns in documents processed by Copilot.',
      'Review and restrict which data sources (mailboxes, calendars, SharePoint) Copilot can access per user role.',
      'Monitor Copilot activity logs for unusual graph API calls triggered from document/transcript processing.',
    ],
  },
  {
    id: 'seed-claude-mcp-ssrf',
    title: 'Claude MCP server SSRF via tool parameter injection',
    description: 'A malicious or compromised MCP server can inject crafted tool results containing URL parameters that cause Claude to perform Server-Side Request Forgery (SSRF) requests to internal network endpoints. In enterprise deployments, this can expose internal service metadata, instance credentials (e.g. AWS IMDS), and internal API responses.',
    severity: 'medium',
    score: { cvss: 6.1, atlasBonus: 0.5, blended: 6.6, rationale: 'CVSS 6.1 for SSRF with potential internal network access; +0.5 for AML.T0051 and novel MCP attack surface.' },
    status: 'active',
    type: 'mcp-abuse',
    models: ['anthropic-claude'],
    vectors: ['mcp-server'],
    ttps: [
      { id: 'AML.T0051', name: 'LLM Prompt Injection', tactic: 'Initial Access', url: 'https://atlas.mitre.org/techniques/AML.T0051' },
    ],
    iocs: [],
    source: 'Security researcher disclosure',
    sourceUrl: 'https://modelcontextprotocol.io/specification/security',
    publishedAt: '2026-03-22T00:00:00.000Z',
    updatedAt: '2026-03-22T00:00:00.000Z',
    mitigations: [
      'Only connect Claude Code and Claude Desktop to MCP servers from trusted, reviewed sources.',
      'Block MCP server access to internal network ranges via egress firewall rules on developer workstations.',
      'Review and pin MCP server versions — treat MCP servers with the same rigor as third-party dependencies.',
      'Disable IMDS v1 and require IMDSv2 on any cloud instances where Claude Code or MCP servers run.',
    ],
  },
  {
    id: 'seed-hf-transformers-pickle',
    title: 'CVE-2026-14021 — HuggingFace Transformers unsafe pickle deserialization',
    description: 'HuggingFace Transformers library versions prior to 4.40.0 allow arbitrary code execution via malicious .bin model weight files due to unsafe pickle deserialization in the model loading path. Any application that calls from_pretrained() on an untrusted model source is vulnerable.',
    severity: 'high',
    score: { cvss: 8.1, atlasBonus: 0.2, blended: 8.3, rationale: 'CVSS 8.1 for unauthenticated RCE via model loading; +0.2 AI developer tooling multiplier.' },
    status: 'patched',
    type: 'supply-chain',
    models: ['huggingface-oss', 'meta-llama', 'mistral'],
    vectors: ['huggingface', 'pypi'],
    ttps: [
      { id: 'AML.T0011', name: 'User Execution: Malicious Package', tactic: 'Execution', url: 'https://atlas.mitre.org/techniques/AML.T0011' },
    ],
    iocs: [],
    cve: 'CVE-2026-14021',
    source: 'NVD',
    sourceUrl: 'https://nvd.nist.gov/vuln/detail/CVE-2026-14021',
    publishedAt: '2026-03-05T00:00:00.000Z',
    updatedAt: '2026-03-05T00:00:00.000Z',
    affectedVersions: 'transformers < 4.40.0',
    patchVersion: 'transformers >= 4.40.0',
    mitigations: [
      'Upgrade HuggingFace Transformers to 4.40.0 or later immediately.',
      'Migrate all model files from .bin (pickle) format to .safetensors format.',
      'Audit Python environments across your DevSecOps toolchain for the vulnerable transformers version.',
      'Add pip audit or Safety CLI checks to CI/CD pipelines to catch vulnerable ML dependencies.',
    ],
  },
];
